#ifndef CYGONCE_PKGCONF_DEVS_SPI_CORTEXM_STM32_H
#define CYGONCE_PKGCONF_DEVS_SPI_CORTEXM_STM32_H
/*
 * File <pkgconf/devs_spi_cortexm_stm32.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_DEVS_SPI_CORTEXM_STM32_PIN_TOGGLE_RATE 25
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_PIN_TOGGLE_RATE_25
#define CYGHWR_DEVS_SPI_CORTEXM_STM32_BUS1 1
#define CYGHWR_DEVS_SPI_CORTEXM_STM32_BUS1_CS_GPIOS SPI_CS(A, 4)
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_BBUF_SIZE 0
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_BBUF_SIZE_0
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_TXINTR_PRI 69
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_TXINTR_PRI_69
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_RXINTR_PRI 134
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_BUS1_RXINTR_PRI_134
#define CYGPKG_DEVS_SPI_CORTEXM_STM32_OPTIONS 1

#endif
