#ifndef CYGONCE_PKGCONF_DEVS_FLASH_SPI_AT25DFXXX_H
#define CYGONCE_PKGCONF_DEVS_FLASH_SPI_AT25DFXXX_H
/*
 * File <pkgconf/devs_flash_spi_at25dfxxx.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGHWR_DEVS_FLASH_SPI_AT25DFXXX_DEVICE 1
#define CYGHWR_DEVS_FLASH_SPI_AT25DFXXX_DEVICE_1
#define CYGPKG_DEVS_FLASH_SPI_AT25DFXXX_BLOCK_SIZE 65536
#define CYGPKG_DEVS_FLASH_SPI_AT25DFXXX_BLOCK_SIZE_65536
#define CYGPKG_DEVS_FLASH_SPI_AT25DFXXX_READ_MODE FAST
#define CYGPKG_DEVS_FLASH_SPI_AT25DFXXX_READ_MODE_FAST
#define CYGNUM_DEVS_FLASH_SPI_AT25DFXXX_READ_BLOCK_SIZE 0
#define CYGNUM_DEVS_FLASH_SPI_AT25DFXXX_READ_BLOCK_SIZE_0

#endif
