#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_STM32_STM32F4KEYSTONE_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_STM32_STM32F4KEYSTONE_H
/*
 * File <pkgconf/hal_cortexm_stm32_stm32f4keystone.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "Cortex-M4"
#define HAL_PLATFORM_BOARD  "STMicroelectronics STM32F4-keystone"
#define HAL_PLATFORM_EXTRA  ""
#define CYGNUM_HAL_CORTEXM_STM32_IMAGE_ADDRESS 0x08000000
#define CYGNUM_HAL_CORTEXM_STM32_IMAGE_ADDRESS_0x08000000
#define CYGARC_HAL_CORTEXM_STM32_INPUT_CLOCK 8000000
#define CYGARC_HAL_CORTEXM_STM32_INPUT_CLOCK_8000000
#define CYGNUM_HAL_CORTEXM_STM32_FLASH_WAIT_STATES 5
#define CYGNUM_HAL_CORTEXM_STM32_FLASH_WAIT_STATES_5
#define CYGHWR_HAL_CORTEXM_STM32_FLASH 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGPKG_HAL_CORTEXM_STM32_STM32F4KEYSTONE_OPTIONS 1

#endif
