#ifndef CYGONCE_PKGCONF_IO_SERIAL_CORTEXM_STM32_H
#define CYGONCE_PKGCONF_IO_SERIAL_CORTEXM_STM32_H
/*
 * File <pkgconf/io_serial_cortexm_stm32.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_IO_SERIAL_CORTEXM_STM32_SERIAL0 1
#define CYGDAT_IO_SERIAL_CORTEXM_STM32_SERIAL0_NAME "/dev/ser0"
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_BAUD 115200
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_BAUD_115200
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_BUFSIZE 128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_BUFSIZE_128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_INT_PRI 128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL0_INT_PRI_128
#define CYGPKG_IO_SERIAL_CORTEXM_STM32_SERIAL1 1
#define CYGDAT_IO_SERIAL_CORTEXM_STM32_SERIAL1_NAME "/dev/ser1"
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_BAUD 115200
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_BAUD_115200
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_BUFSIZE 128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_BUFSIZE_128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_INT_PRI 128
#define CYGNUM_IO_SERIAL_CORTEXM_STM32_SERIAL1_INT_PRI_128
#define CYGPKG_IO_SERIAL_CORTEXM_STM32_OPTIONS 1
#define CYGPKG_IO_SERIAL_CORTEXM_STM32_TESTING 1
#define CYGPRI_SER_TEST_CRASH_ID "stm32"
#define CYGPRI_SER_TEST_SER_DEV "/dev/ser0"
#define CYGPRI_SER_TEST_TTY_DEV "/dev/tty0"

#endif
