#ifndef CYGONCE_PKGCONF_NET_LWIP_H
#define CYGONCE_PKGCONF_NET_LWIP_H
/*
 * File <pkgconf/net_lwip.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGFUN_LWIP_MODE_SIMPLE 1
#define CYGFUN_LWIP_SIO 1
#define CYGIMP_LWIP_ENDIAN_BY_HAL 1
#define CYGPKG_LWIP_RAW 1
#define CYGNUM_LWIP_RAW_TTL 255
#define CYGNUM_LWIP_RAW_TTL_255
#define CYGPKG_LWIP_ARP 1
#define CYGNUM_LWIP_ARP_TABLE_SIZE 10
#define CYGNUM_LWIP_ARP_TABLE_SIZE_10
#define CYGFUN_LWIP_ARP_QUEUEING 1
#define CYGFUN_LWIP_ETHARP_TRUST_IP_MAC 1
#define CYGFUN_LWIP_IP_OPTIONS_ALLOWED 1
#define CYGFUN_LWIP_IP_REASSEMBLY 1
#define CYGFUN_LWIP_IP_FRAG 1
#define CYGNUM_LWIP_IP_REASS_MAXAGE 3
#define CYGNUM_LWIP_IP_REASS_MAXAGE_3
#define CYGNUM_LWIP_IP_REASS_MAX_PBUFS 10
#define CYGNUM_LWIP_IP_REASS_MAX_PBUFS_10
#define CYGFUN_LWIP_IP_FRAG_USES_STATIC_BUF 1
#define CYGNUM_LWIP_IP_FRAG_MAX_MTU 1500
#define CYGNUM_LWIP_IP_FRAG_MAX_MTU_1500
#define CYGNUM_LWIP_IP_DEFAULT_TTL 255
#define CYGNUM_LWIP_IP_DEFAULT_TTL_255
#define CYGPKG_LWIP_ICMP 1
#define CYGNUM_LWIP_ICMP_TTL 255
#define CYGNUM_LWIP_ICMP_TTL_255
#define CYGPKG_LWIP_IGMP 1
#define CYGPKG_LWIP_UDP 1
#define CYGFUN_LWIP_UDPLITE 1
#define CYGNUM_LWIP_UDP_TTL 255
#define CYGNUM_LWIP_UDP_TTL_255
#define CYGPKG_LWIP_TCP 1
#define CYGNUM_LWIP_TCP_TTL 255
#define CYGNUM_LWIP_TCP_TTL_255
#define CYGNUM_LWIP_TCP_WND 2144
#define CYGNUM_LWIP_TCP_WND_2144
#define CYGNUM_LWIP_TCP_MAXRTX 12
#define CYGNUM_LWIP_TCP_MAXRTX_12
#define CYGNUM_LWIP_TCP_SYNMAXRTX 6
#define CYGNUM_LWIP_TCP_SYNMAXRTX_6
#define CYGFUN_LWIP_TCP_QUEUE_OOSEQ 1
#define CYGNUM_LWIP_TCP_MSS 536
#define CYGNUM_LWIP_TCP_MSS_536
#define CYGFUN_LWIP_TCP_CALCULATE_EFF_SEND_MSS 1
#define CYGNUM_LWIP_TCP_SND_BUF 1072
#define CYGNUM_LWIP_TCP_SND_BUF_1072
#define CYGNUM_LWIP_TCP_SND_QUEUELEN 8
#define CYGNUM_LWIP_TCP_SND_QUEUELEN_8
#define CYGNUM_LWIP_TCP_SNDLOWAT 536
#define CYGNUM_LWIP_TCP_SNDLOWAT_536
#define CYGNUM_LWIP_TCP_WND_UPDATE_THRESHOLD 1
#define CYGFUN_LWIP_CALLBACK_API 1
#define CYGPKG_LWIP_DHCP 1
#define CYGFUN_LWIP_DHCP_DOES_ARP_CHECK 1
#define CYGPKG_LWIP_AUTOIP 1
#define CYGFUN_LWIP_DHCP_AUTOIP_COOP 1
#define CYGNUM_LWIP_DHCP_AUTOIP_COOP_TRIES 9
#define CYGNUM_LWIP_DHCP_AUTOIP_COOP_TRIES_9
#define CYGPKG_LWIP_DNS 1
#define CYGNUM_LWIP_DNS_TABLE_SIZE 4
#define CYGNUM_LWIP_DNS_TABLE_SIZE_4
#define CYGNUM_LWIP_DNS_MAX_NAME_LENGTH 256
#define CYGNUM_LWIP_DNS_MAX_NAME_LENGTH_256
#define CYGNUM_LWIP_DNS_MAX_SERVERS 2
#define CYGNUM_LWIP_DNS_MAX_SERVERS_2
#define CYGFUN_LWIP_DNS_DOES_NAME_CHECK 1
#define CYGNUM_LWIP_DNS_USES_STATIC_BUF 1
#define CYGNUM_LWIP_DNS_USES_STATIC_BUF_1
#define CYGNUM_LWIP_DNS_MSG_SIZE 512
#define CYGNUM_LWIP_DNS_MSG_SIZE_512
#define CYGIMP_LWIP_NETIF_HOSTNAME 1
#define CYGFUN_LWIP_NETIF_STATUS_CALLBACK 1
#define CYGFUN_LWIP_NETIF_LINK_CALLBACK 1
#define CYGPKG_LWIP_PPP 1
#define CYGFUN_LWIP_PPPOS_SUPPORT 1
#define CYGDAT_LWIP_PPPOS_DEV "/dev/ser5"
#define CYGNUM_LWIP_NUM_PPP 1
#define CYGNUM_LWIP_NUM_PPP_1
#define CYGFUN_LWIP_PAP_SUPPORT 1
#define CYGFUN_LWIP_CHAP_SUPPORT 1
#define CYGFUN_LWIP_MD5_SUPPORT 1
#define CYGNUM_LWIP_MEM_ALIGNMENT 4
#define CYGNUM_LWIP_MEM_ALIGNMENT_4
#define CYGNUM_LWIP_MEM_SIZE 4608
#define CYGNUM_LWIP_MEM_SIZE_4608
#define CYGDBG_LWIP_MEMP_OVERFLOW_CHECK 0
#define CYGDBG_LWIP_MEMP_OVERFLOW_CHECK_0
#define CYGNUM_LWIP_MEMP_NUM_PBUF 16
#define CYGNUM_LWIP_MEMP_NUM_PBUF_16
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB 5
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_5
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_LISTEN 8
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_LISTEN_8
#define CYGNUM_LWIP_MEMP_NUM_TCP_SEG 16
#define CYGNUM_LWIP_MEMP_NUM_TCP_SEG_16
#define CYGNUM_LWIP_MEMP_NUM_REASSDATA 5
#define CYGNUM_LWIP_MEMP_NUM_REASSDATA_5
#define CYGNUM_LWIP_MEMP_NUM_ARP_QUEUE 30
#define CYGNUM_LWIP_MEMP_NUM_ARP_QUEUE_30
#define CYGNUM_LWIP_MEMP_NUM_IGMP_GROUP 8
#define CYGNUM_LWIP_MEMP_NUM_IGMP_GROUP_8
#define CYGNUM_LWIP_MEMP_NUM_CORE_SYS_TIMEOUT 9
#define CYGNUM_LWIP_MEMP_NUM_CORE_SYS_TIMEOUT_9
#define CYGNUM_LWIP_MEMP_NUM_USER_SYS_TIMEOUT 0
#define CYGNUM_LWIP_MEMP_NUM_USER_SYS_TIMEOUT_0
#define CYGNUM_LWIP_MEMP_NUM_NETBUF 2
#define CYGNUM_LWIP_MEMP_NUM_NETBUF_2
#define CYGNUM_LWIP_MEMP_NUM_NETCONN 4
#define CYGNUM_LWIP_MEMP_NUM_NETCONN_4
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG_API 8
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG_API_8
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG_INPKT 8
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG_INPKT_8
#define CYGNUM_LWIP_PBUF_POOL_SIZE 16
#define CYGNUM_LWIP_PBUF_POOL_SIZE_16
#define CYGNUM_LWIP_VARMEMPOOL_SIZE 2048
#define CYGNUM_LWIP_VARMEMPOOL_SIZE_2048
#define CYGNUM_LWIP_PBUF_LINK_HLEN 0
#define CYGNUM_LWIP_PBUF_LINK_HLEN_0
#define CYGNUM_LWIP_PBUF_POOL_BUFSIZE 576
#define CYGNUM_LWIP_PBUF_POOL_BUFSIZE_576
#define CYGIMP_LWIP_CHECKSUM_GEN_IP 1
#define CYGIMP_LWIP_CHECKSUM_GEN_UDP 1
#define CYGIMP_LWIP_CHECKSUM_GEN_TCP 1
#define CYGIMP_LWIP_CHECKSUM_CHECK_IP 1
#define CYGIMP_LWIP_CHECKSUM_CHECK_UDP 1
#define CYGIMP_LWIP_CHECKSUM_CHECK_TCP 1
#define CYGFUN_LWIP_SHOW_NETIF_CONFIG 1
#define CYGDAT_NET_LWIP_PPP_TEST_APN "gprs.swisscom.ch"
#define CYGDAT_NET_LWIP_PPP_TEST_NUMBER "*99#"
#define CYGDAT_NET_LWIP_PPP_TEST_USERNAME "gprs"
#define CYGDAT_NET_LWIP_PPP_TEST_PASSWORD "gprs"
#define CYGDAT_NET_LWIP_PPP_TEST_HOST "www.ping.ch"

#endif
